- name: OBS Studio
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install required package ffmpeg
      become: yes
      apt:
        package: ffmpeg
        update_cache: yes

    - name: Add APT package source (Ubuntu)
      become: yes
      apt_repository:
        repo: ppa:obsproject/obs-studio
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install OBS Studio
      become: yes
      apt:
        package: obs-studio
