- name: OBS Studio
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install required package ffmpeg
      become: true
      apt:
        package: ffmpeg
        update_cache: true

    - name: Add APT package source (Ubuntu)
      become: true
      apt_repository:
        repo: ppa:obsproject/obs-studio
      register: apt_repository

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install OBS Studio
      become: true
      apt:
        package: obs-studio

    - name: Add script for resetting the video device for OBS Studio
      copy:
        src: reset-video.sh
        mode: 0755
        dest: ~/bin/reset-video.sh

    - name: Add useful aliases
      blockinfile:
        path: ~/.bash_aliases
        create: yes
        marker: "### {mark} Ansible managed: obs-studio helper aliases"
        block: |
          alias reset-video='~/bin/reset-video.sh'
