- name: Teams
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Microsoft APT package key
      become: true
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Teams APT package repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
        filename: teams
        update_cache: no
      register: apt_repository
      when: not is_wsl

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: not is_wsl and apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Teams
      become: true
      apt:
        package: teams
      when: not is_wsl
