- name: Azure (azcopy)
  hosts: 127.0.0.1
  connection: local

  vars:
    azcopy_version: 10.10.0

  tasks:
    - name: Create azcopy folder
      become: yes
      file:
        path: /opt/azcopy
        state: directory

    - name: Download azcopy
      become: yes
      unarchive:
        src: https://aka.ms/downloadazcopy-v10-linux/
        dest: /opt/azcopy
        mode: 0777
        remote_src: yes
        creates: /opt/azcopy/azcopy_linux_amd64_{{ azcopy_version }}/azcopy

    - name: Create shortcut to azcopy
      become: yes
      file:
        path: /usr/local/bin/azcopy
        src: /opt/azcopy/azcopy_linux_amd64_{{ azcopy_version }}/azcopy
        state: link
