- name: git
  hosts: 127.0.0.1
  connection: local

  vars:
    - RIPGREP_VERSION: "11.0.2"

  tasks:
    - name: Add Git APT package repository (Ubuntu)
      become: yes
      apt_repository:
        repo: ppa:git-core/ppa
        filename: git
        update_cache: no
      register: apt_repository_1
      when: ansible_distribution == 'Ubuntu'

    - name: Add Backports repository (Debian Stretch)
      become: yes
      apt_repository:
        repo: deb http://deb.debian.org/debian stretch-backports main
        filename: backports
        update_cache: no
      register: apt_repository_2
      when: ansible_distribution_release == 'stretch'

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository_1.changed or apt_repository_2.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install APT packages
      become: yes
      apt:
        package:
          - git
          - git-gui
          - git-lfs
          - gitk
        state: latest

    - name: Install ripgrep (Ubuntu 18.04 / Debian Stretch)
      become: yes
      apt:
        deb: https://github.com/BurntSushi/ripgrep/releases/download/{{ RIPGREP_VERSION }}/ripgrep_{{ RIPGREP_VERSION }}_amd64.deb
      when: ansible_distribution_release == 'bionic' or ansible_distribution_release == 'stretch'

    - name: Install ripgrep (others)
      become: yes
      apt:
        package: ripgrep
      when: ansible_distribution_release != 'bionic' and ansible_distribution_release != 'stretch'

    - name: Add global git config file
      copy:
        src: gitconfig
        dest: $HOME/.gitconfig
        mode: 0644
