- name: Postman
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install Postman
      become: true
      unarchive:
        src: https://dl.pstmn.io/download/latest/linux64
        dest: /opt
        remote_src: true
        creates: /opt/Postman/Postman
      when: not is_wsl

    - name: Ensure local applications folder exists
      become: true
      file:
        path: /usr/local/share/applications
        state: directory
      when: not is_wsl

    - name: Add Postman desktop file
      become: true
      copy:
        src: postman.desktop
        dest: /usr/local/share/applications/postman.desktop
      when: not is_wsl
