#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: Configure machine for development work (with customizations)
  hosts: 127.0.0.1
  connection: local

- import_playbook: _jz_no_customization.yaml
- import_playbook: _jz_envar.yaml

# Install tmux
- import_playbook: tmux/core.yaml

# Install Atom
- import_playbook: atom/core.yaml

# Install fonts for starship
- import_playbook: fonts/core.yaml

# Install starship
- import_playbook: starship/core.yaml

# TODO: atom configuration - git clone git@gitlab.clearballot.com:jz/atom.git $HOME/.atom
# TODO: install Retext
# TODO: install Vault and signing script
# TODO: open ufw for port 22
# TODO: copy over ssh keys and config, set the correct perms, and do `ssh add`
