#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: Configure machine for development work (with customizations)
  hosts: 127.0.0.1
  connection: local

- import_playbook: _jz_no_customization.yaml
- import_playbook: _jz_core.yaml

# Install tmux
- import_playbook: tmux/core.yaml

# Install Atom
- import_playbook: atom/core.yaml

# Install fonts for starship
- import_playbook: fonts/core.yaml

# Install starship
- import_playbook: starship/core.yaml

# Install python packages
- import_playbook: python-packages/core.yaml

# Install terraform
- import_playbook: terraform/core.yaml

# Install cherrytree
- import_playbook: cherrytree/core.yaml

# Install slack
- import_playbook: slack/core.yaml

# Install vault
- import_playbook: vault/core.yaml

# Install stuff for yubikey
- import_playbook: yubico/core.yaml

# Install Signal companion app
- import_playbook: signal/core.yaml

# TODO: map Super Escape to "Switch windows of an app directly" via the Settings UI app (Keyboard pane)
# TODO: copy over ssh keys and config, set the correct perms, and do `ssh add`
# TODO: atom configuration - git clone git@gitlab.clearballot.com:jz/atom.git $HOME/.atom
# TODO: Vault signing script

# Manual stuff
# Open up Firefox, log in and sync
# Log into vault via the UI, copy token, from a shell do "vault login" and give it the token
# git config --global user.name "Jesse Zoldak"
# git config --global user.email "jesse.zoldak@clearballot.com"
