#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: Configure machine for development work
  hosts: 127.0.0.1
  connection: local

- import_playbook: core.yaml

- import_playbook: azure/az.yaml
- import_playbook: azure/azshell.yaml
- import_playbook: azure/azcopy.yaml
- import_playbook: azure/storage-explorer.yaml
- import_playbook: azure/az-aks.yaml

- import_playbook: brave/core.yaml
- import_playbook: broot/core.yaml
- import_playbook: docker/core.yaml
- import_playbook: flameshot/core.yaml
- import_playbook: git/core.yaml
- import_playbook: golang/core.yaml
- import_playbook: postman/core.yaml
- import_playbook: python/core.yaml

- import_playbook: alacritty/core.yaml
- import_playbook: alacritty/customization-jz.yaml

- import_playbook: google-chrome/core.yaml
- import_playbook: remmina/core.yaml
- import_playbook: slack/core.yaml
- import_playbook: vlc/core.yaml
- import_playbook: zoom/core.yaml
- import_playbook: forticlient/core.yaml
- import_playbook: helm/core.yaml
- import_playbook: spotify/core.yaml
