- name: Environment variable customization
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install other helpful packages (macOS)
      homebrew:
        name:
          - graphviz
          - ldns  # provides drill (similar to ldnsutils)
          - magic-wormhole
          - nmap
          - gnupg  # provides scdaemon
          - shellcheck
          - speedtest-cli
          - tree
          - whois
          - wireguard-tools
          - gh
        state: present
