- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl=false

    - name: Create ~/bin
      file:
        path: ~/bin
        state: directory
        mode: 0700

    - name: Add ~/bin to PATH
      lineinfile:
        path: ~/.zshrc
        line: export PATH=$PATH:~/bin
        regexp: '^export PATH=\$PATH:~/bin$'
        state: present

    - name: Install core Homebrew packages
      homebrew:
        name:
          - gnupg
          - htop
          - inetutils
          - jq
          - p7zip
        state: present

    - name: Ensure ~/.hushlogin exists
      file:
        path: ~/.hushlogin
        state: touch
