- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Create ~/bin
      file:
        path: ~/bin
        state: directory
        mode: 0700

    - name: Add ~/bin to PATH
      lineinfile:
        path: ~/.zshrc
        line: export PATH=$PATH:~/bin
        regexp: '^export PATH=\$PATH:~/bin$'
        state: present

    - name: Install core Homebrew packages
      homebrew:
        name:
          - black
          - broot
          - gh
          - gnupg
          - go
          - graphviz
          - htop
          - inetutils
          - jq
          - ldns  # provides drill
          - magic-wormhole
          - nmap
          - p7zip
          - pre-commit
          - ripgrep
          - shellcheck
          - speedtest-cli
          - tree
          - whois
          - wireguard-tools
        state: present
