- name: Configure my machine how I like it
  hosts: 127.0.0.1
  connection: local

- import_playbook: core.yaml
- import_playbook: wezterm.yaml
- import_playbook: starship.yaml
# - import_playbook: docker.yaml. # install via self service
- import_playbook: terraform.yaml
