- name: Starship
  hosts: 127.0.0.1
  connection: local

  vars:
    fonts_apt:
      - fonts-powerline
      - fonts-firacode
      
  tasks:
    - name: Install Powerline and Firacode fonts (via APT)
      become: yes
      apt:
        package: "{{ item }}"
      loop: "{{ fonts_apt }}"
    
    - name: Install Starship via snap
      become: yes
      snap:
        name: starship

    - name: Initialize Starship during shell config
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: initialize starship"
        block: |
          eval "$(starship init bash)"
