- name: Starship
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install via snap
      become: yes
      snap:
        name: starship

    - name: Initialize starship during shell config
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: initialize starship"
        block: |
          eval "$(starship init bash)"
