- name: Terraform
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
        dest: /tmp/terraform_0.13.5_linux_amd64.zip
        checksum: sha256:f7b7a7b1bfbf5d78151cfe3d1d463140b5fd6a354e71a7de2b5644e652ca5147
      register: terraform_download

    - name: Move the terraform binary into the path
      become: yes
      unarchive:
        src: /tmp/terraform_0.13.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
