- name: Terraform
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /tmp/terraform_0.12.28_linux_amd64.zip
        checksum: sha256:be99da1439a60942b8d23f63eba1ea05ff42160744116e84f46fc24f1a8011b6
      register: terraform_download

    - name: Move the terraform binary into the path
      become: yes
      unarchive:
        src: /tmp/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
