- name: Terraform
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_linux_amd64.zip
        dest: /tmp/terraform_0.15.1_linux_amd64.zip
        checksum: sha256:1ff798791abf518fb0b5d9958ec8327b7213f1c91fb5235923e91cc96c59ef2c
      register: terraform_download

    - name: Move the terraform binary into the path
      become: true
      unarchive:
        src: /tmp/terraform_0.15.1_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
