- name: Terraform
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip
        dest: /tmp/terraform_0.14.2_linux_amd64.zip
        checksum: sha256:6f380c0c7a846f9e0aedb98a2073d2cbd7d1e2dc0e070273f9325f1b69e668b2
      register: terraform_download

    - name: Move the terraform binary into the path
      become: yes
      unarchive:
        src: /tmp/terraform_0.14.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
