- name: Terraform
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
        dest: /tmp/terraform_1.0.9_linux_amd64.zip
        checksum: sha256:f06ac64c6a14ed6a923d255788e4a5daefa2b50e35f32d7a3b5a2f9a5a91e255
      register: terraform_download

    - name: Move the terraform binary into the path
      become: true
      unarchive:
        src: /tmp/terraform_1.0.9_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
