---
- name: CyberChef
  hosts: 127.0.0.1
  connection: local

  vars:
    cc_version: v10.5.2
    cc_dest: ~/cyberchef

  tasks:
    - name: Create CyberChef directory if it does not exist
      ansible.builtin.file:
        path: "{{ cc_dest }}"
        state: directory
        mode: "0755"

    - name: Install CyberChef
      unarchive:
        src: "https://github.com/gchq/CyberChef/releases/download/{{ cc_version }}/CyberChef_{{ cc_version }}.zip"
        dest: "{{ cc_dest }}"
        remote_src: true
        creates: "{{ cc_dest }}/CyberChef_{{ cc_version }}.html"
