- name: Insync
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Insync APT package key (Ubuntu)
      become: true
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: ACCAF35C
      when: not is_wsl and ansible_distribution == 'Ubuntu'

    - name: Add Insync APT package repository (Ubuntu)
      become: true
      apt_repository:
        repo: deb http://apt.insynchq.com/ubuntu bionic non-free contrib
        filename: insync
        update_cache: no
      register: apt_repository
      when: not is_wsl and ansible_distribution == 'Ubuntu'

    - name: Update APT package list (Ubuntu)
      become: true
      apt:
        update_cache: true
      when: not is_wsl and apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Insync (Ubuntu)
      become: true
      apt:
        package:
          - insync
          - insync-nautilus
      when: not is_wsl and ansible_distribution == 'Ubuntu'
