- name: Zoom
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install Zoom
      become: true
      apt:
        deb: https://zoom.us/client/latest/zoom_amd64.deb
      when: not is_wsl
