- name: Docker
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Docker pre-requisites
      become: true
      apt:
        package: gnupg-agent

    - name: Add Docker APT package key
      become: true
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

    - name: Add Docker APT package repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        filename: docker
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Docker CLI components
      become: true
      apt:
        package:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose

    - name: Install Docker engine
      become: true
      apt:
        package: docker-ce

    - name: Enable Docker engine for current user
      become: true
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes

    - name: Add custom Docker commands
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Docker customization"
        block: |
          docker-clean() {
            _containers=$(docker ps --quiet --filter 'status=exited')
            [[ -z ${_containers// } ]] || docker rm $_containers

            _images=$(docker images --all --quiet --filter 'dangling=true')
            [[ -z ${_images// } ]] || docker rmi $_images
          }

    - name: adding existing user '{{ ansible_user }}' to group docker
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes
