- name: Ghidra
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Amazon Corretto APT package key
      become: true
      apt_key:
        url: https://apt.corretto.aws/corretto.key

    - name: Add Amazon Corretto APT package repository
      become: true
      apt_repository:
        repo: deb https://apt.corretto.aws stable main
        update_cache: true

    - name: Install Amazon Coretto Java 11
      become: true
      apt:
        package: java-11-amazon-corretto-jdk

    - name: Download Ghidra
      get_url:
        url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.4_build/ghidra_10.1.4_PUBLIC_20220519.zip
        dest: /tmp/ghidra_10.1.4_PUBLIC_20220519.zip
        checksum: sha256:91556c77c7b00f376ca101a6026c0d079efbf24a35b09daaf80bda897318c1f1
      register: ghidra_download

    - name: Unzip the Ghidra package under my home dir
      unarchive:
        src: /tmp/ghidra_10.1.4_PUBLIC_20220519.zip
        dest: ~/.
        remote_src: true
