- name: Fonts
  hosts: 127.0.0.1
  connection: local

  vars:
    fonts_apt:
      - fonts-powerline
      - fonts-firacode

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install Powerline and Firacode fonts (via APT)
      become: true
      apt:
        package: "{{ item }}"
      loop: "{{ fonts_apt }}"
      when: not is_wsl
