- name: Beyond Compare
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Scooter Software APT package key
      become: true
      apt_key:
        url: https://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware

    - name: Add Beyond Compare 4 APT package repository
      become: true
      apt_repository:
        repo: deb http://www.scootersoftware.com/ bcompare4 non-free
        filename: scootersoftware
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Beyond Compare 4
      become: true
      apt:
        package: bcompare
