- name: Flameshot
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install Flameshot
      become: true
      apt:
        package: flameshot
      when: not is_wsl and ansible_distribution_release != 'stretch'
