---
- name: BurpSuite
  hosts: 127.0.0.1
  connection: local

  vars:
    burp_version: 2022.6.1
    burp_install_sh_sha256: ced6f082fa26f7b4806cc484cedd965d204d86c796ada14ee4c6a84fcf37c4a0

  tasks:
    - name: Download BurpSuite install script
      get_url:
        url: "https://portswigger-cdn.net/burp/releases/download?product=community&version={{ burp_version }}&type=Linux"
        dest: /tmp/burpsuite_community_linux.sh
        checksum: sha256:{{ burp_install_sh_sha256 }}
        mode: 0777
      register: burp_download

    - name: Run the burp install script
      shell:
        chdir: /tmp
        cmd: /tmp/burpsuite_community_linux.sh
        creates: $HOME/BurpSuiteCommunity
