- name: kubectl
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Kubernetes APT package key
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Add Kubernetes APT package repository
      become: true
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        filename: kubernetes
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install kubectl
      become: true
      apt:
        package: kubectl

    - name: Enable bash completion for kubectl
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Enable kubectl auto-complete"
        block: |
          eval "$(kubectl completion bash)"
