- name: Vault
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download Vault
      get_url:
        url: https://releases.hashicorp.com/vault/1.4.0/vault_1.4.0_linux_amd64.zip
        dest: /tmp/vault_1.4.0_linux_amd64.zip
        checksum: sha256:8f739c4850bab35e971e27c8120908f48f247b07717d19aabad1110e9966cded
      register: vault_download

    - name: Move the vault binary into the path
      become: yes
      unarchive:
        src: /tmp/vault_1.4.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes

    - name: Add script for signing ssh key
      copy:
        src: sign.sh
        mode: 0755
        dest: /home/jz/bin/sign.sh

    - name: Add script for generating 1 hr mtls employee cert
      copy:
        src: cert.sh
        mode: 0755
        dest: /home/jz/bin/cert.sh

    - name: Add useful aliases
      blockinfile:
        path: ~/.bash_aliases
        create: yes
        marker: "### {mark} Ansible managed: core aliases"
        block: |
          alias cert='/home/jz/bin/cert.sh'
          alias sign='/home/jz/bin/sign.sh'
