- name: Vault
  hosts: 127.0.0.1
  connection: local

  vars:
    vault_version: 1.9.3
    vault_checksum: 16059f245fb4df2800fe6ba320ea66aba9c2615348e37bcfd42754591a528639

  tasks:
    - name: Download Vault
      get_url:
        url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
        dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
        checksum: sha256:{{vault_checksum}}
      register: vault_download

    - name: Move the vault binary into the path
      become: true
      unarchive:
        src: /tmp/vault_{{vault_version}}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true

    - name: Add script for signing ssh key
      copy:
        src: sign.sh
        mode: 0755
        dest: /home/jz/bin/sign.sh

    - name: Add script for generating 1 hr mtls employee cert
      copy:
        src: cert.sh
        mode: 0755
        dest: /home/jz/bin/cert.sh

    - name: Add useful aliases
      blockinfile:
        path: ~/.bash_aliases
        create: yes
        marker: "### {mark} Ansible managed: core aliases"
        block: |
          alias cert='/home/jz/bin/cert.sh'
          alias sign='/home/jz/bin/sign.sh'
