- name: Fulcrum
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Fulcrum packages via homebrew
      homebrew:
        name: "{{ item }}"
      loop:
      - gawk
      - helm
      - istioctl
      - kubectl
      - pre-commit
      - shellcheck
      - terraform-docs
      - tfenv
      - tflint
      - tfsec
