- name: Misc odds and ends
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install core packages
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - dos2unix
        - gcc-11
        - gh
        - make
        - python3-virtualenv
        - wslu
        - zip

    - name: Ensure that the locale en_US.UTF-8 is in the generate file
      become: yes
      ansible.builtin.lineinfile:
        path: "/etc/locale.gen"
        line: "en_US.UTF-8 UTF-8"
        state: present
      register: locale_gen

    - name: Generate en_US.UTF-8 locale
      ansible.builtin.command: update-locale
      become: yes
      when: locale_gen.changed

    - name: Add LANG environment variable to shell configuration file
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: set locale"
        block: |
          export LANG=en_US.UTF-8

    - name: Add bash aliases
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: misc bash aliases"
        block: |
          alias rm-tg-cache='find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;'
          alias rm-pycache='find . -type d -name "__pycache__" -prune -exec rm -rf {} \;'
          alias rm-pyc='find . -type f -name "*.pyc" -exec rm -f {} \;'
          alias tgp='terragrunt plan -out=plan.tfplan'
          alias tga='terragrunt apply plan.tfplan'
