- name: .NET Core
  hosts: 127.0.0.1
  connection: local

  vars:
    dotnet_versions:
      - "2.1"
      - "3.1"
      - "5.0"
    dotnet_distro_version: "{{ ansible_distribution_major_version if ansible_distribution == 'Debian' else ansible_distribution_version }}"    # MSFT uses '19.04' for Ubuntu, and just '10' for Debian

  tasks:
    - name: Add Microsoft APT package key
      become: true
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Microsoft APT package repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/{{ ansible_distribution | lower }}/{{ dotnet_distro_version }}/prod {{ ansible_distribution_release }} main
        filename: microsoft-prod
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install .NET Core SDKs
      become: true
      apt:
        package: dotnet-sdk-{{ item }}
      register: dotnet_sdk_installed
      loop: "{{ dotnet_versions }}"

    - name: Perform first-run experience
      command: dotnet new
      when: dotnet_sdk_installed.changed

    - name: Update environment for .NET Core
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: .NET Core enhancement"
        block: |
          export PATH=$PATH:$HOME/.dotnet/tools
