- name: Firefox
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install via snap
      snap:
        name: firefox
      when: not is_wsl
