- name: K9S
  hosts: 127.0.0.1
  connection: local

  vars:
    k9s_version: v0.25.18
    k9s_archive_checksum: d288aacc368ab6b243fc9e7ecd17b53fa34a813509c2dc3023171085db83cf9d

  tasks:
    - name: Download K9S
      get_url:
        url: https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_x86_64.tar.gz
        dest: /tmp/k9s_Linux_x86_64.tar.gz
        checksum: sha256:{{ k9s_archive_checksum }}
      register: k9s_download

    - name: Extract k9s
      unarchive:
        src: /tmp/k9s_Linux_x86_64.tar.gz
        dest: $HOME/bin
        exclude:
        - README.md
        - LICENSE
        creates: $HOME/bin/k9s
