- name: Helm
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Helm APT package key
      become: true
      apt_key:
        url: https://baltocdn.com/helm/signing.asc

    - name: Add Helm APT package repository
      become: true
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        filename: helm-stable-debian
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Helm
      become: true
      apt:
        package: helm
