- name: Python3.9
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add deadsnakes APT package key
      become: true
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: F23C5A6CF475977595C89F51BA6932366A755776

    - name: Add deadsnakes APT package repository
      become: true
      apt_repository:
        repo: deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ ansible_distribution_release }} main
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: true
      apt:
        update_cache: true
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Python
      become: true
      apt: name="python3.9" state=present
