- name: Python3.8
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add deadsnakes APT package key
      become: yes
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: F23C5A6CF475977595C89F51BA6932366A755776

    - name: Add deadsnakes APT package repository
      become: yes
      apt_repository:
        repo: deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ ansible_distribution_release }} main
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Python
      become: yes
      apt: name="python3.8" state=present

    - name: Create alternatives link for 3.6
      become: yes
      alternatives:
        name: python3
        link: /usr/bin/python3
        path: /usr/bin/python3.6
        priority: 1

    - name: Create alternatives link for 3.8
      become: yes
      alternatives:
        name: python3
        link: /usr/bin/python3
        path: /usr/bin/python3.8
        priority: 10
